spring.application.name=ecom-cart
server.port=8080

# PostgreSQL settings
spring.datasource.url=jdbc:postgresql://localhost:5432/ecom_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Settings
app.jwt-secret=bFZ2QnZPK0Z4UXNzMml0K3FPQ01yd2tqQ2dJanBTODd5VzVkZG5XSCtURT0=
app.jwt-expiration-milliseconds=604800000

logging.level.org.springframework.security=DEBUG

# Razorpay Settings
razorpay.key.id=rzp_test_lMGutHM2h07Px7
razorpay.key.secret=k2ViN7nDEegFVz4qZlLou4f4

